language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t djmenkveld/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true djmenkveld/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-eu-central-1-009981322445"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


  